import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map.Entry;

public class Frequencies {
	HashMap<Character, Double> frequenceLetter = new HashMap<Character, Double>();
	List<Entry<Character, Double>> list;

	String texte = "POURQUOI AVOIR ATTENDU LA FIN DU MOIS DE JUIN POUR ANNONCER LA CANDIDATURE ALORS QUE DES FEVRIER LORS DE LA PRESENTATION DU PROJET A LHOTEL DE VILLE DE PARIS LE CHOIX SEMBLAIT DEJA PRIS"
			+ "BERNARD LAPASSET  IL Y AVAIT EFFECTIVEMENT PAS MAL DE TEMPS QUE NOUS SENTIONS QUE LE DOSSIER ETAIT MUR ET QUE NOUS POUVIONS LANNONCER PARCE QUE NOUS AVIONS LACCORD DE LETAT ET DE LA VILLE QUI SONT LES DEUX SIGNATAIRES AVEC LE COMITE OLYMPIQUE DE LA CANDIDATURE MAIS IL ETAIT AUSSI IMPORTANT DAVOIR LE TEMPS DECHANGER AVEC LES AUTRES PARTENAIRES NOUS DEVONS TRAVAILLER EN COLLECTIF AVEC UN PRINCIPE  CE SONT LES ATHLETES ET LE MONDE SPORTIF QUI SONT DEVANT"
			+ "A QUEL MOMENT DONNEREZ VOUS PLUS DE PRECISIONS SUR LE DOSSIER DE CANDIDATURE QUELLES SONT LES PROCHAINES ETAPES"
			+ "IL FAUT COMPTER JUSQUA DEBUT OU MI SEPTEMBRE POUR AVOIR LA PREMIERE VERSION COMPLETE DU DOSSIER NOUS MENONS UN TRAVAIL DAPPROCHE AVANT POUR TRAVAILLER SUR LA PARTIE MARITIME PUISQUE SIX DOSSIERS SERONT PRESENTES POUR LES EPREUVES DE VOILE OU DE NAGE EN EAU LIBRE NOUS AURONS AUSSI UNE APPROCHE PLUS DIRECTE AVEC UN CERTAIN NOMBRE DE COMMUNES QUE NOUS VOYONS REGULIEREMENT AFIN DE DEFINIR DES PRINCIPES ET VOIR COMMENT ELLES PEUVENT Y REPONDRE AVANT QUE NOUS SOYONS EVENTUELLEMENT AMENES A LES RETENIR"
			+ "LEMPLACEMENT DU VILLAGE OLYMPIQUE UN CHANTIER PRESSENTI EN SEINE SAINT DENIS SERA DONC CONNU EN SEPTEMBRE AU PLUS TARD"
			+ "OUI NOUS SOMMES EN PLEIN DEDANS MAIS NOUS NE POUVONS PAS VRAIMENT DONNER DES ELEMENTS DINFOS POUR LINSTANT CEST TROP CONFIDENTIEL DANS LA MESURE OU AUJOURDHUI IL NY A DE CERTITUDE SUR AUCUN DES SITES"
			+ "LE COUT DU DOSSIER DE CANDIDATURE A ETE ESTIME A  MILLIONS DEUROS"
			+ "OUI SUR DEUX ANS IL EST POUR LINSTANT ETABLI SUR LA BASE DES QUATRE ACTIONNAIRES NOUS NE SOMMES PAS ENCORE DANS UNE CONFIGURATION TELLE QUELLE SERA DANS LE DOSSIER DEFINITIF AVEC UN GIP GROUPEMENT DINTERET PUBLIC OU UN GIE GROUPEMENT DINTERET ECONOMIQUE NOUS SOMMES EN TRAIN DE DISCUTER AVEC LETAT SUR LES FORMES JURIDIQUES DE NOTRE PROCHAINE ASSOCIATION DANS LE CADRE DE LASSOCIATION TEMPORAIRE AUJOURDHUI NOUS AVONS DEJA RECU  MILLIONS DEUROS    EUROS DU MOUVEMENT SPORTIF LA MEME CHOSE DE LA VILLE DE LA REGION ET DE LETAT"
			+ "COMMENT GARANTIR LA PROBITE DUNE CANDIDATURE ALORS QUE LATTRIBUTION DES COUPES DU MONDE DE FOOTBALL A RECEMMENT FAIT SCANDALE "
			+ "CE NEST PAS COMPLIQUE IL FAUT RESPECTER LES REGLES ETABLIES LA TRANSPARENCE EST LUN DES ELEMENTS DE LAGENDA  UNE FEUILLE DE ROUTE PRESENTEE EN DECEMBRE  PAR LE CIO POUR ASSAINIR LES JEUX OLYMPIQUES JE NOTE DEJA UN SIGNE FORT QUI MONTRE LA FACON DONT EST ABORDEE CETTE NOTION DE TRANSPARENCE  LE CIO A PUBLIE LE MONTANT DES INDEMNITES QUIL VA LAISSER A SES MEMBRES ET A SON PRESIDENT THOMAS BACH"
			+ "AVEZ VOUS PREVU UNE COMMISSION DE CONTROLE INDEPENDANTE POUR FACILITER LE SUVI DE LA CANDIDATURE"
			+ "JATTENDS DE VOIR CE QUE LE CIO NOUS DEMANDE MAIS TOUS LES CAS DE FIGURE SONT ENVISAGES"
			+ "ET QUEN EST IL DUN REFERENDUM POUR ASSOCIER DAVANTAGE LES FRANCILIENS A LEVENEMENT"
			+ "JE NE CROIS PAS QUIL Y EN AURA UN ON SEST PLUTOT MIS DACCORD AVEC LA VILLE POUR METTRE EN PLACE DES CONSULTATIONS REGULIERES A LECHELLE DUNE VILLE DUNE REGION OU DUN SECTEUR DACTIVITE MAIS CE NE DEVRAIT PAS ETRE UN REFERENDUM CAR CEST UN MODELE EXTREMEMENT LOURD IL FAUT AU MOINS  POURCENT DE PARTICIPANTS POUR QUUN REFERENDUM SOIT RECONNU ET ENCORE FAUT IL POSER LA BONNE QUESTION LIDEE AU LIEU DE DEMANDER AUX HABITANTS DE REPONDRE OUI  OU NON  A UNE QUESTION IL SAGIRA DE LES FAIRE PARTICIPER A DES DEBATS SUR DES QUESTIONS PRECISES CONCERNANT TEL OU TEL ASPECT DU DOSSIER";

	String texte2 = "LE GENERAL SORTI UN BADGE ET SE DIRIGEA VERS L UNE DES PORTES ENTOUREES DE PEINTURE JAUNE IL GLISSA LE BADGE DANS LA FENTE SITUEE A DROITE LA PORTE S OUVRIT UNE DIZAINE DE MILITAIRES ARMEES JUSQU AUX DENTS ETAIENT POSTEES DERRIERE INTERNET N EST PAS LE SEUL RESEAU IL EXISTE UN AUTRE RESEAU PLUS PERFORMANT JE NE T APPRENDRAIS RIEN EN TE DISANT QU INTERNET A ETE CREE PAR L ARMEE AMERICAINE DANS UN BUT MILITAIRE INTERNET N ETAIT QUE LE PROTOTYPE UN AUTRE RESEAU A ETE CREE POUR LES MILITAIRES COMPLETEMENT INDEPENDANT D INTERNET TIRANT DES LECONS DU PREMIER RESEAU LE PETIT FRERE D INTERNET EST DEVENUE UN GRAND FRERE IL SORT DE SON LIT LES YEUX DANS UN BROUILLARD LONDONIEN AVANCE JUSQU A LA SALLE DE BAIN DONT LA BAIGNOIRE A ETE REMPLIE CINQ MINUTES AVANT PAR L ORDINATEUR DE LA MAISON ET VA DIRECTEMENT PRENDRE UN BAIN UN BAIN MOUSSANT COMME TOUT LES MATINS UN BAIN BIEN CHAUD ET COMME IL EST TROP GRAND POUR SA BAIGNOIRE SES PIEDS DEPASSENT QUELQUES MINUTES PLUS TARD IL S ENDORT AUCUN RISQUE DE NOYADE LA GRANDE PORTE S OUVRIT LOURDEMENT EN COULISSANT SUR LE COTE GAUCHE SANS FAIRE LE MOINDRE BRUIT DERRIERE LA PORTE UNE NOUVELLE ROUTE ECLAIREE PAR DE MULTIPLES PROJECTEURS ACCROCHES DE CHAQUE COTES S ENFONCAIT DANS LES PROFONDEURS DE CET OUVRAGE CETTE ROUTE ETAIT FAITE DE ZIGZAG INCESSANT CERTAINEMENT POUR EMPECHER LE SOUFFLE D UNE BOMBE ATOMIQUE PENSA DAVID FLORENCE AVAIT L ESPRIT UN PEU MELANGE ENTRE CE PRELUDE QUI NE LUI APPORTAIT QUE DES QUESTIONS SANS REPONSE ET SON DAVID PRELUDE AVAIT REVEILLE BRUSQUEMENT UN SENTIMENT QUE FLORENCE AVAIT AU PLUS PROFOND D ELLE DESORMAIS ELLE VOULAIT SAVOIR CONNAITRE LA VERITE ET SEULEMENT ALORS CETTE BOULE DE NERF COINCEE DANS L ESTOMAC POURRAIT S EN ALLER ";

	public String getTexte() {
		return texte;
	}

	public String getTexte2() {
		return texte2;
	}

	public Frequencies() {
		frequenceLetter.put(' ', 16.024);
		frequenceLetter.put('A', 7.636);
		frequenceLetter.put('B', 0.901);
		frequenceLetter.put('C', 3.260);
		frequenceLetter.put('D', 3.669);
		frequenceLetter.put('E', 14.715);
		frequenceLetter.put('F', 1.066);
		frequenceLetter.put('G', 0.866);
		frequenceLetter.put('H', 0.737);
		frequenceLetter.put('I', 7.529);
		frequenceLetter.put('J', 0.545);
		frequenceLetter.put('K', 0.049);
		frequenceLetter.put('L', 5.456);
		frequenceLetter.put('M', 2.968);
		frequenceLetter.put('N', 7.095);
		frequenceLetter.put('O', 5.378);
		frequenceLetter.put('P', 3.021);
		frequenceLetter.put('Q', 1.362);
		frequenceLetter.put('R', 6.553);
		frequenceLetter.put('S', 7.948);
		frequenceLetter.put('T', 7.244);
		frequenceLetter.put('U', 6.311);
		frequenceLetter.put('V', 1.628);
		frequenceLetter.put('W', 0.114);
		frequenceLetter.put('X', 0.387);
		frequenceLetter.put('Y', 0.308);
		frequenceLetter.put('Z', 0.136);

		list = new ArrayList<Entry<Character, Double>>(
				frequenceLetter.entrySet());
	}
	public HashMap<Character, Double> getFrequenceLetter() {
		return frequenceLetter;
	}

	public void print() {
		System.out.println(frequenceLetter);
	}

	public List<Entry<Character, Double>> getList() {
		return list;
	}

	public void printSorted() {
		Collections.sort(list, new ComparatorNew());
		System.out.println(list);
	}

	public class ComparatorNew implements Comparator<Entry<Character, Double>> {
		@Override
		public int compare(Entry<Character, Double> arg0,
				Entry<Character, Double> arg1) {
			return arg1.getValue().compareTo(arg0.getValue());
		}
	}
}
